### ISSUE TITLE
Example to pass custom header per request

### ISSUE THREAD

**Issue by astavria4** [artilleryio/artillery-examples#1]
Hi, 

I want to say that this tool is awesome! 

The below is my config file:

config:
    target: "http://localhost:8080/v1/graphql"
    phases:
      - duration: 5
        arrivalRate: 1
    processor: "./index.js"
scenarios:
    - name: "GraphQL Query load test"
      flow:
        - function: "testCases"
        - loop:
            - post:
                url: "/"
                json:
                query: '{{ $loopElement.query }}'
                variables: '{{ $loopElement.variables }}' 
            - log: "----------------------------------"
            - log: "Sent a request to the Query: {{ $loopElement.name }}"
            - log: 'And variable {{ $loopElement.variables }}'
          over: cases

My requirement is to pass a new header value for each virtual user created. 

I know that you can use beforeScenario which is meant to be run before each scenario execution (by each virtual user).

I also know that beforeRequest can also be used to change the header on the fly. 

Is beforeRequest or beforeScenario the best approach for my requirment? 

Can you show me an example of how to change the header values for each virtual user? 

So each virtual user has a query, parameter and a header value?

Thanks,
Alex

**Comment by hassy** [comment]
`beforeScenario` runs once for each VU, and does not have access to individual request objects. You can however create new variables with `beforeScenario` hooks, and then use them in templates as normal (with `"{{ myVariable }}"`).

To create a variable, update `userContext.vars` object in your `beforeScenario` hook, e.g.:

```
function myBeforeScenarioHook(userContext, events, done) {
  // make myVariable available in the scenario:
  userContext.vars.myVariable = 'hello';
  return done();
}
```

`beforeScenario` will allow you to set unique headers & query parameters per request - that may work better, depending on your requirements.

**Comment by hassy** [comment]
Please feel free to open a PR with an example! 🚀

**Comment by cfryerdev** [comment]
Closing as there is an example in the repo now :) Thanks for the suggestion
